/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui_nezet;

import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import modell.Konyv;
import modell.Konyvtar;

/**
 *
 * @author pille
 */
public class KonyvtarForm extends javax.swing.JFrame {
    private Konyvtar konyvtar;
    
    /**
     * Creates new form KonyvtarForm
     */
    public KonyvtarForm() {
        initComponents();
        
        konyvtar = new Konyvtar();
        
        // Új könyv:
        szerzo2Szovegdoboz();
        
        // Könyvtár:
        konyvtarKonyveinekListazasa();
        cmbSzerzokFeltoltese();
    }

    // Új könyv:
    public void szerzo2Szovegdoboz() {
        txtfSzerzo1.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                String szoveg = txtfSzerzo1.getText();
                if (!(szoveg.isEmpty())) {
                    txtfSzerzo2.setEnabled(true);
                } else {
                    txtfSzerzo2.setEnabled(false);
                }
            }
        });
    }
    
    // Könyvtár:
    public void konyvtarKonyveinekListazasa() {
        DefaultListModel konyvtarKonyvei = new DefaultListModel();
        for(Konyv konyv : konyvtar.getKonyvek()) {
            konyvtarKonyvei.addElement(konyv.getCim());
        }
        listKonyvtarKonyvei.setModel(konyvtarKonyvei);
    }
    
    public void cmbSzerzokFeltoltese() {
        Set<String> osszesSzerzo = new HashSet<>();
        
        cmbSzerzok.removeAllItems();
        
        for(Konyv konyv : konyvtar.getKonyvek()) {
            osszesSzerzo.add(konyv.getSzerzo1());
            if(!(konyv.getSzerzo2() == null)) osszesSzerzo.add(konyv.getSzerzo2());
        }
        
        for(String szerzo : osszesSzerzo) {
            cmbSzerzok.addItem(szerzo);
        }
    }
    
    public void szerzoKonyveinekListazasa(String szerzo) {
        DefaultListModel szerzoKonyvei = new DefaultListModel();
        for(Konyv konyv : konyvtar.getKonyvek()) {
            if(konyv.getSzerzo1().equals(szerzo) || (!(konyv.getSzerzo2() == null) && konyv.getSzerzo2().equals(szerzo))) {
                szerzoKonyvei.addElement(konyv.getCim());
            }
        }
        if(listSzerzoKonyvei.getModel().getSize() == 0) {
            for(int i = 0; i < listSzerzoKonyvei.getModel().getSize(); i++) {
                listSzerzoKonyvei.remove(i);
            }
        }
        
        listSzerzoKonyvei.setModel(szerzoKonyvei);
    }
    
    public void konyvekMentese(JList<String> lista) throws FileNotFoundException, IOException {
        JFileChooser filechooser = new JFileChooser();
        int valasz = filechooser.showSaveDialog(rootPane);
        if(valasz == JFileChooser.APPROVE_OPTION) {
            ArrayList<String> konyvcimek = new ArrayList<>();
            for(int i = 0; i < lista.getModel().getSize(); i++) {
                // System.out.println(lista.getModel().getElementAt(i));
                konyvcimek.add(lista.getModel().getElementAt(i));
            }
            
            File fajl = filechooser.getSelectedFile();

            BufferedWriter bufferedwriter = new BufferedWriter(new FileWriter(fajl));
            for(String konyvcim : konyvcimek) {
                String cim;
                if(konyvcim != konyvcimek.get(konyvcimek.size() - 1)) cim = String.format("%s\n", konyvcim);
                else cim = konyvcim;
                bufferedwriter.write(cim);
            }
            bufferedwriter.close();
        }    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblCim = new javax.swing.JLabel();
        lblSzerzo1 = new javax.swing.JLabel();
        lblSzerzo2 = new javax.swing.JLabel();
        lblKiadasEve = new javax.swing.JLabel();
        lblVisszajelzes = new javax.swing.JLabel();
        txtfCim = new javax.swing.JTextField();
        txtfSzerzo1 = new javax.swing.JTextField();
        txtfSzerzo2 = new javax.swing.JTextField();
        spKiadasEve = new javax.swing.JSpinner();
        lblVisszajelzesUzenet = new javax.swing.JLabel();
        btnUjKonyv = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblKonyvtarKonyvei = new javax.swing.JLabel();
        cmbSzerzok = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listKonyvtarKonyvei = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSzerzoKonyvei = new javax.swing.JList<>();
        btnSzerzoKonyveiMentes = new javax.swing.JButton();
        btnKonyvtarKonyveiMentes = new javax.swing.JButton();
        btnSzerzoKeresese = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuitemFrissites = new javax.swing.JMenuItem();
        menuitemKilepes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Könyvtár");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCim.setText("Cím:");

        lblSzerzo1.setText("1. szerző:");

        lblSzerzo2.setText("2. szerző:");

        lblKiadasEve.setText("Kiadás éve:");

        lblVisszajelzes.setText("Visszajelzés:");

        txtfSzerzo2.setEnabled(false);

        spKiadasEve.setModel(new javax.swing.SpinnerNumberModel(1950, 1950, 2023, 1));

        lblVisszajelzesUzenet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVisszajelzesUzenet.setText("...");

        btnUjKonyv.setText("Új könyv felvétele");
        btnUjKonyv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUjKonyvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKiadasEve)
                    .addComponent(lblSzerzo2)
                    .addComponent(lblSzerzo1)
                    .addComponent(lblCim)
                    .addComponent(lblVisszajelzes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfCim)
                    .addComponent(txtfSzerzo1)
                    .addComponent(txtfSzerzo2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spKiadasEve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(btnUjKonyv))
                    .addComponent(lblVisszajelzesUzenet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCim)
                    .addComponent(txtfCim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSzerzo1)
                    .addComponent(txtfSzerzo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSzerzo2)
                    .addComponent(txtfSzerzo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKiadasEve)
                    .addComponent(spKiadasEve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUjKonyv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVisszajelzes)
                    .addComponent(lblVisszajelzesUzenet))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Új könyv", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKonyvtarKonyvei.setText("Könyvtár könyvei:");

        cmbSzerzok.setName(""); // NOI18N

        jScrollPane1.setViewportView(listKonyvtarKonyvei);

        jScrollPane2.setViewportView(listSzerzoKonyvei);

        btnSzerzoKonyveiMentes.setText("Mentés");
        btnSzerzoKonyveiMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSzerzoKonyveiMentesActionPerformed(evt);
            }
        });

        btnKonyvtarKonyveiMentes.setText("Mentés");
        btnKonyvtarKonyveiMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonyvtarKonyveiMentesActionPerformed(evt);
            }
        });

        btnSzerzoKeresese.setText("Keresés");
        btnSzerzoKeresese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSzerzoKereseseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnKonyvtarKonyveiMentes, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblKonyvtarKonyvei)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbSzerzok, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSzerzoKonyveiMentes, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnSzerzoKeresese, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbSzerzok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKonyvtarKonyvei, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSzerzoKeresese)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSzerzoKonyveiMentes)
                    .addComponent(btnKonyvtarKonyveiMentes))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Könyvtár", jPanel2);

        jMenu1.setText("Fájl");

        menuitemFrissites.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuitemFrissites.setText("Frissítés");
        menuitemFrissites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemFrissitesActionPerformed(evt);
            }
        });
        jMenu1.add(menuitemFrissites);

        menuitemKilepes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuitemKilepes.setText("Kilépés");
        menuitemKilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemKilepesActionPerformed(evt);
            }
        });
        jMenu1.add(menuitemKilepes);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUjKonyvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUjKonyvActionPerformed
        String cim = txtfCim.getText();
        String szerzo1 = txtfSzerzo1.getText();
        String szerzo2 = txtfSzerzo2.getText();
        int kiadasEve = (int) spKiadasEve.getValue();
        
        if(cim.isEmpty()) lblVisszajelzesUzenet.setText("A cím nem lehet üres.");
        else if(szerzo1.isEmpty()) lblVisszajelzesUzenet.setText("Az első szerző nem lehet üres.");
        else {
            Konyv konyv = new Konyv(cim, szerzo1, szerzo2, kiadasEve);
            
            if(konyvtar.getKonyvek().isEmpty()) konyvtar.konyvHozzaadas(konyv);
            else {
                if(konyvtar.vanAzonos(konyv)) {
                    lblVisszajelzesUzenet.setText("Már van ilyen című könyv.");
                    txtfCim.setText("");
                }
                else {
                    konyvtar.konyvHozzaadas(konyv);
                    lblVisszajelzesUzenet.setText("Új könyv hozzáadva.");
                }
            }
        }
    }//GEN-LAST:event_btnUjKonyvActionPerformed

    private void menuitemKilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemKilepesActionPerformed
        int valasz = JOptionPane.showConfirmDialog(rootPane, "Biztosan ki szeretnél lépni?", "Kilépés", 0);
        if(valasz == JOptionPane.YES_OPTION) System.exit(0);
    }//GEN-LAST:event_menuitemKilepesActionPerformed

    private void btnKonyvtarKonyveiMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonyvtarKonyveiMentesActionPerformed
        try {
            konyvekMentese(listKonyvtarKonyvei);
        } catch (IOException ex) {
            Logger.getLogger(KonyvtarForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnKonyvtarKonyveiMentesActionPerformed

    private void btnSzerzoKonyveiMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSzerzoKonyveiMentesActionPerformed
        try {
            konyvekMentese(listSzerzoKonyvei);
        } catch (IOException ex) {
            Logger.getLogger(KonyvtarForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSzerzoKonyveiMentesActionPerformed

    private void btnSzerzoKereseseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSzerzoKereseseActionPerformed
        String kivalasztottSzerzo = (String) cmbSzerzok.getSelectedItem();
        szerzoKonyveinekListazasa(kivalasztottSzerzo);
    }//GEN-LAST:event_btnSzerzoKereseseActionPerformed

    private void menuitemFrissitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemFrissitesActionPerformed
        konyvtarKonyveinekListazasa();
        cmbSzerzokFeltoltese();
    }//GEN-LAST:event_menuitemFrissitesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonyvtarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonyvtarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonyvtarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonyvtarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonyvtarForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonyvtarKonyveiMentes;
    private javax.swing.JButton btnSzerzoKeresese;
    private javax.swing.JButton btnSzerzoKonyveiMentes;
    private javax.swing.JButton btnUjKonyv;
    private javax.swing.JComboBox<String> cmbSzerzok;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCim;
    private javax.swing.JLabel lblKiadasEve;
    private javax.swing.JLabel lblKonyvtarKonyvei;
    private javax.swing.JLabel lblSzerzo1;
    private javax.swing.JLabel lblSzerzo2;
    private javax.swing.JLabel lblVisszajelzes;
    private javax.swing.JLabel lblVisszajelzesUzenet;
    private javax.swing.JList<String> listKonyvtarKonyvei;
    private javax.swing.JList<String> listSzerzoKonyvei;
    private javax.swing.JMenuItem menuitemFrissites;
    private javax.swing.JMenuItem menuitemKilepes;
    private javax.swing.JSpinner spKiadasEve;
    private javax.swing.JTextField txtfCim;
    private javax.swing.JTextField txtfSzerzo1;
    private javax.swing.JTextField txtfSzerzo2;
    // End of variables declaration//GEN-END:variables
}
